baseURL: http://dev.org.app/
languageCode: en-us
title: Oh geez, really?
theme: dev-ogr

build:
  buildStats:
    enable: true
  cachebusters:
    - source: assets/notwatching/hugo_stats\.json
      target: css
    - source: (postcss|tailwind)\.config\.js
      target: css
markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      autoHeadingID: true
module:
  mounts:
    - source: assets
      target: assets
    - disableWatch: true
      source: hugo_stats.json
      target: assets/notwatching/hugo_stats.json
